apiVersion: apps/v1
kind: Deployment
metadata:
   name: toleration-pod
   # these are replica set labels
   labels:
      envronment:  toleration-pod

spec:
   replicas: 1
   # these labels are used to select pods
   selector: 
      matchLabels:
           envronment:  roboshop-dev
#like pod defination we are not giving pod name here
   template:
      metadata:
        labels:
           envronment:  roboshop-dev
      spec:
        nodeSelector:
          topology.kubernetes.io/zone=us-east-1d
        containers:
        - name: nginx
          image: nginx   
        tolerations:
        - key: "project"
          operator: "Equal"
          value: "roboshop"
          effect: "NoSchedule"    
 
---

apiVersion: v1
kind: Service
metadata: 
   name: nginx  # service name


spec:
  selector:
     envronment:  roboshop-dev
  ports:
     - protocol: TCP
       port: 80 # sevice port
       targetPort: 80 # container port   forwart req to another container