apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-pod
  labels:
    environment: toleration-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: roboshop-dev
  template:
    metadata:
      labels:
        environment: roboshop-dev
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1d
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshp"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
