# redis1 ---> node 1
#redis2 ---> node 2

#webserver app1 ----> redis 1
#webserver app2 ----->present in redis2 but not with app1
#  ip-192-168-8-237.ec2.internal    node 1
#  ip-192-168-45-212.ec2.internal   node 2

apiVersion: v1
kind: Pod
metadata:
  name: redis1
  #namespace: roboshop
  labels:
    cache: redis-1
spec:
  nodeSelector:
    server: primary

  tolerations:
  - key: "server"
    operator: "Equal"
    value: "primary"
    effect: "NoSchedule"

  containers:
  - name: redis
    image: redis:7.0
    ports:
    - containerPort: 6379

---
apiVersion: v1
kind: Pod
metadata:
  name: redis2
  labels:
    cache: redis2
spec:
  nodeSelector:
    server: secondary

  containers:
  - name: redis
    image: redis:7.0
    ports:
    - containerPort: 6379

---


apiVersion: v1
kind: Pod
metadata:
  name: web1
  #namespace: roboshop
  labels:
    webserver: nginx-1
spec:
  nodeSelector:
    server: primary

  tolerations:
  - key: "server"
    operator: "Equal"
    value: "primary"
    effect: "NoSchedule"

  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: web2
  #namespace: roboshop
  labels:
    webserver: nginx-2
spec:
  nodeSelector:
    server: secondary


  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

